### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by LJWatson** [hannalaakso/accessible-timeout-warning#1]
The frequency of the live region updates makes it difficult to use a screen reader. Suggest that the visible time updates are not included in the live region, but instead a hidden live region is created that updates less frequently (perhaps every 15 or 30 seconds).

**Comment by hannalaakso** [comment]
Thanks @LJWatson. The component now uses a hidden region that updates every 15 seconds - the main countdown that updates every second is hidden with `aria-hidden`.
